name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - blogbranch

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true



      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: 安装依赖
        run: npm ci

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > src/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: blogshow # 部署到 blogshow 分支，因为 main（这里对应的是blogbranch） 分支存放的一般是源码，而 blogbranch 分支则用来存放生成的静态文件
          folder: src/.vuepress/dist # vuepress 生成的静态文件存放的地方